### PR TITLE
created react todo app

### PR DESCRIPTION
**Pull request by sonyco-4u**
In this PR I did the following:

Created components in class form, later translated to functions
Created functionalities of adding todos, editing todos, deleting todos, and the checkbox
Created local storage
Added css for styling, with different methods
Used lifecycle methods and hooks

### CODE REVIEW

**Comment by Oklukeok** [comment]
Hello Anthony! You did a great job! Everything works fine.
There is only one little detail:
The buttons to delete the task are not align and sometimes is hard to click them.
image

**Comment by sonyco-4u** [comment]
Thank you for your Review I have made the corrections

**Comment by sonyco-4u** [comment]
@Oklukeok Can you check my recent corrections and certify my Project

**Comment by Oklukeok** [comment]
Awesome! you can merge it!

image

**Comment by sonyco-4u** [comment]
Thanks for certifying my project

**Pull request merged**
